export default {
	TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
	TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
	NOTION_TOKEN: process.env.NOTION_TOKEN,
	NOTION_DATABASE_ID: process.env.NOTION_DATABASE_ID,
};
